# Generated by Django 3.2.3 on 2021-05-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_request', '0002_alter_uuid_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuid',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
