# Generated by Django 3.2.3 on 2021-05-27 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('handle_request', '0003_alter_uuid_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuid',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
