# Generated by Django 3.2.3 on 2021-05-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_request', '0006_alter_uuid_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='uuid',
            name='status',
            field=models.CharField(choices=[('Cr', 'Created'), ('Pn', 'Pending')], max_length=2, null=True),
        ),
    ]
